name: ChangeBot
description: Monitor websites for changes and get notified via webhooks or ntfy.sh. Powered by GitHub Actions and Bun.
author: Philipp Gartz <https://github.com/phlgr>
inputs:
  command:
    required: true
    description: The command to run (update or check).
    default: update
runs:
  using: composite
  steps:
    # Checkout the calling repo (where .changebotrc.yml and snapshots live)
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        fetch-depth: 0

    - run: |
        git fetch origin snapshots:snapshots 2>/dev/null || git checkout -b snapshots
        git checkout snapshots
      shell: bash

       # Get config from main (not committed, just for reading)
    - run: git checkout origin/main -- .changebotrc.yml
      shell: bash

    # Fetch the monitor code
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        repository: phlgr/changebot-monitor
        path: .changebot-monitor

    - uses: oven-sh/setup-bun@3d267786b128fe76c2f16a390aa2448b815359f3 # v2

    - run: bun install --frozen-lockfile
      shell: bash
      working-directory: .changebot-monitor

    # Run the monitor from the calling repo's root (so git operations work)
    # Environment variables are inherited from the calling workflow
    - run: bun run .changebot-monitor/src/monitor.ts --${{ inputs.command }}
      shell: bash
branding:
  icon: search
  color: blue